/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "keypad.h"
#include "LCD.h"
#include "SevenSeg.h"


void wait(int x)
{
	int i,j;
	for (i=0;i<x;i++)
		for(j=0;j<x;j++);
}

void clk_Init(void)
{
	//Enable clock for GPIO A
	RCC_GPIOA_CLK_EN() ;
	//Enable clock for GPIO B
	RCC_GPIOB_CLK_EN() ;
}




int main(void)
{

	clk_Init();
	wait(10);
	HAL_LCD_Init();
	wait(10);
	HAL_KEYPAD_Init();
	wait(10);
	HAL_LCD_WRITE_STR("Keypad is Ready");
	wait(50);
	HAL_LCD_CLEAR();
	unsigned char Key;
	uint32_t count =0;
	while(1)
	{
		Key = HAL_KEYPAD_GetChar();
		if(Key == 'N');
		else if(Key == '!')
		{
			HAL_LCD_CLEAR();
			count=0;
		}
		else
		{
			HAL_LCD_WRITE_CHAR(Key);
			count++;
		}
		if(count == 16)
		{
			HAL_LCD_GOTO_XY(2,0);
		}
		else if(count==32)
		{
			HAL_LCD_CLEAR();
			HAL_LCD_GOTO_XY(1,0);
			count =0;
		}



	}


}
