/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define SYSCTL_RCGC2_R			(*((volatile unsigned long*) 0x400FE108))
#define GPIO_PORTF_DIR_R		(*((volatile unsigned long*) 0x40025400))
#define GPIO_PORTF_DEN_R		(*((volatile unsigned long*) 0x4002551C))
#define GPIO_PORTF_DATA_R		(*((volatile unsigned long*) 0x400253FC))






int main()
{
	volatile int i;
	SYSCTL_RCGC2_R = 0x20;
	for (i=0 ; i<20000 ; i++); //delay for the wake up time of GPIO port F
	GPIO_PORTF_DIR_R |= 1<<3;  //DIR is output for PIN no. 3 
	GPIO_PORTF_DEN_R |= 1<<3;  
	while (1)
	{
		GPIO_PORTF_DATA_R |=1<<3;
		for(i = 0 ; i<200000 ; i++);
		GPIO_PORTF_DATA_R &= ~(1<<3);
		for(i = 0 ; i<200000 ; i++);
	}
	
	return 0;
}