/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "keypad.h"
#include "LCD.h"

uint8_t IRQ_flag ;

void wait(int x)
{
	int i,j;
	for (i=0;i<x;i++)
		for(j=0;j<x;j++);
}

void clk_Init(void)
{
	//Enable clock for GPIO A
	RCC_GPIOA_CLK_EN() ;
	//Enable clock for GPIO B
	RCC_GPIOB_CLK_EN() ;
	//Enable clock for AFIO
	RCC_AFIO_CLK_EN();
}

void EXTI9_CALLBACK(void)
{
	IRQ_flag = 1;
	HAL_LCD_WRITE_STR("IRQ EXTI9 Has   Happened _|-");
	wait(500);
}

int main(void)
{

	clk_Init();
	HAL_LCD_Init();
	wait(10);
	HAL_LCD_CLEAR();
	EXTI_PinConfig_t EXTI_Config;
	EXTI_Config.EXTI_PIN = EXTI9_PORTB9;
	EXTI_Config.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_Config.Ptr_IRQ_CALLBACK = EXTI9_CALLBACK;
	EXTI_Config.IRQ_Enable = EXTI_IRQ_ENBALE ;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);

	IRQ_flag = 1;
	while(1)
	{
		if(IRQ_flag == 1)
		{
			HAL_LCD_CLEAR();
			IRQ_flag =0;
		}

	}


}
