/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_F103C6_GPIO_Driver.h"
//#include "STM32_F103C6_EXTI_Driver.h"
//#include "STM32_F103C6_USART_Driver.h"
//#include "STM32_F103C6_SPI_Driver.h"
#include "STM32_F103C6_I2C_Driver.h"
#include "EEPROM.h"
//#include "keypad.h"
//#include "LCD.h"







void wait(int x)
{
	int i,j;
	for (i=0;i<x;i++)
		for(j=0;j<x;j++);
}


void clk_Init(void)
{
	//Enable clock for GPIO A
	RCC_GPIOA_CLK_EN() ;
	//Enable clock for GPIO B
	RCC_GPIOB_CLK_EN() ;
	//Enable clock for AFIO
	RCC_AFIO_CLK_EN();
}


int main(void)
{
	clk_Init();
	//Test Case 1

	uint8_t ch1 [] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8_t ch2 [7] = {0};

	HAL_EEPROM_Init();
	HAL_EEPROM_Write_NBytes(0xAF, ch1, 7);
	HAL_EEPROM_Read_NBytes(0xAF, ch2, 7);

	//Test Case 2

	ch1 [0] = 0xA;
	ch1 [1] = 0xB;
	ch1 [2] = 0xC;
	ch1 [3] = 0xD;


	HAL_EEPROM_Write_NBytes(0xFFF, ch1, 4);
	HAL_EEPROM_Read_NBytes(0xFFF, ch2, 4);


	while(1)
	{

	}


}
