/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"stdint.h"
#include"stdio.h"
#include"stdlib.h"

//GPIO
#define GPIOA_BASE			0x40010800
#define GPIOA_CRL			*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH			*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR			*(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_ODR			*(volatile uint32_t *)(GPIOA_BASE + 0x0C)



#define GPIOB_BASE			0x40010C00
#define GPIOB_CRL			*(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH			*(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_IDR			*(volatile uint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_ODR			*(volatile uint32_t *)(GPIOB_BASE + 0x0C)

//RCC
#define RCC_BASE			0x40021000
#define RCC_APB2ENR			*(volatile uint32_t *)(RCC_BASE + 0x18)

void clock_init()
{

	//  Bit 2 IOPAEN: IO port A clock enable
	//  1: IO port A clock enabled
	RCC_APB2ENR |= (1<<2);
	//  Bit 2 IOPAEN: IO port B clock enable
	//  1: IO port B clock enabled
	RCC_APB2ENR |= (1<<3);
}

void GPIO_init()
{
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOA_ODR = 0x0;

//	GPIOB_CRL=0;
//	GPIOB_CRH=0;
//	GPIOB_ODR=0;

	//INPUT
	//PORT A1 Floating Input
	//00: Input mode (reset state)
	GPIOA_CRL &= ~(0b11<<4);
	//01: Floating input (reset state)
	GPIOA_CRL |= (0b01<<6);

	//PORT A13 Floating Input
	//00: Input mode (reset state
	GPIOA_CRH &= ~(0b11<<20);
	//01: Floating input (reset state)
	GPIOA_CRH |= (0b01<<22);



	//OUTPUT
	//PORT B1 Push Pull Output
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRL |= (0b01<<4);
	//00: General purpose output push-pull
	GPIOB_CRL &= ~(0b11<<6);



	//PORT B13 Push Pull Output
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRH |= (0b01<<20);
	//00: General purpose output push-pull
	GPIOB_CRH &= ~(0b11<<22);




}

void wait()
{
	unsigned int i;
	for(i=0;i<2000;i++);
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		//Port A1 >> Pull Up
		if( ((GPIOA_IDR & (1<<1)) >> 1) == 0)
		{
			//toggle led on Port B1
			GPIOB_ODR ^= (1<<1);
			//single press check
			while(((GPIOA_IDR & (1<<1)) >> 1) == 0);

		}
		//Port A13 >> Pull Down
		if( ((GPIOA_IDR & (1<<13)) >> 13) == 1)
		{
			//toggle led on Port B13
			GPIOB_ODR ^= (1<<13);

		}
		wait();

	}
}
