/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"stdint.h"
#include"stdio.h"
#include"stdlib.h"

//GPIOA
#define GPIOA_BASE			0x40010800
#define GPIOA_CRL			*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH			*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR			*(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_ODR			*(volatile uint32_t *)(GPIOA_BASE + 0x0C)



//GPIOB
#define GPIOB_BASE			0x40010C00
#define GPIOB_CRL			*(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH			*(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_IDR			*(volatile uint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_ODR			*(volatile uint32_t *)(GPIOB_BASE + 0x0C)




//RCC
#define RCC_BASE			0x40021000
#define RCC_APB2ENR			*(volatile uint32_t *)(RCC_BASE + 0x18)




void clk_Init(void)
{
	//Enable clock for GPIO A
	RCC_APB2ENR |= (1<<2);

	//Enable clock for GPIO B
	RCC_APB2ENR |= (1<<3);

}

void GPIO_Init(void)
{
	//Initialize GPIO value to be 0x00000000
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOB_CRH = 0x0;
	GPIOA_IDR = 0x0;
	GPIOB_ODR = 0x0;


	//===============Input Pins===============
	//Configure PIN 1 in GPIOA to be Floating input
	//MODE 00 : Input mode
	GPIOA_CRL &= ~(0b11<<4);
	//CNF 01 : Floating input
	GPIOA_CRL |= (0b01<<6);

	//Configure PIN 13 in GPIOA to be Floating input
	//MODE 00 : Input mode
	GPIOA_CRH &= ~(0b11<<20);
	//CNF 01 : Floating input
	GPIOA_CRH |= (0b01<<22);



	//===============Output Pins===============
	//Configure PIN 1 in GPIOB to be General Purpose Push-Pull
	//MODE 01 : Output mode, max speed 10MHz
	GPIOB_CRL |= (0b01<<4);
	//CNF 00 : General Purpose Output push-pull
	GPIOB_CRL &= ~(0b11<<6);

	//Configure PIN 13 in GPIOB to be General Purpose Push-Pull
	//MODE 01 : Output mode, max speed 10MHz
	GPIOB_CRH |= (0b01<<20);
	//CNF 00 :  General Purpose Output push-pull
	GPIOB_CRH &= ~(0b11<<22);

}

void wait()
{
	int i;
	for (i=0;i<2000;i++);
}



int main(void)
{
	clk_Init();
	GPIO_Init();

	while(1)
	{
		//PORT A Pin 1 Connected to external Pull-Up Resistance (default = 1)
		if ( ( (GPIOA_IDR & (1<<1)) >> 1) == 0 ) // should be single press
		{
			GPIOB_ODR ^= (1<<1);
			//Loop until state change , so continuous pressing doesn't register as multiple presses
			while(( (GPIOA_IDR & (1<<1)) >> 1) == 0);
		}

		//PORT A Pin 13 Connected to external Pull-Down Resistance (default = 0)
		if ( ( (GPIOA_IDR & (1<<13)) >> 13) == 1 ) // should be Multi press
		{
			GPIOB_ODR ^= (1<<13);
		}

		wait();

	}
}


